= A YANG Data Model for the Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD)
:doctype: internet-draft
:abbrev: IGMP & MLD YANG Module
:name: draft-ietf-pim-igmp-mld-yang-15
:status: standard
:intended-series: standard
:submission-type: IETF
:ipr: trust200902
:instance: https://dx.doi.org/10.17487/rfc8652
:instance: urn:issn:2070-1721
:revdate: 2019-01-01T00:00:00Z
:workgroup: PIM Working Group
:keyword: YANG, IGMP, MLD, multicast, data model, ietf-igmp-mld, network management, routing
:xml-lang: en
:consensus: true
:index-include: true
:sort-refs: true
:sym-refs: true
:toc-include: true
:toc-depth: 3
:show-on-front-page: true
:fullname: Xufeng Liu
:initials: X.
:surname: Liu
:affiliation: Volta Networks
:email: xufeng.liu.ietf@gmail.com
:fullname_2: Feng Guo
:initials_2: F.
:surname_2: Guo
:affiliation_2: Huawei Technologies
:affiliation_abbrev_2: Huawei
:email_2: guofeng@huawei.com
:address_2: Huawei Bldg., No. 156 Beiqing Rd.\ Haidian District + \
Beijing + \
China + \
100095
:fullname_3: Mahesh Sivakumar
:initials_3: M.
:surname_3: Sivakumar
:affiliation_3: Juniper Networks
:affiliation_abbrev_3: Juniper
:email_3: sivakumar.mahesh@gmail.com
:address_3: 1133 Innovation Way + \
Sunnyvale + \
California + \
United States of America
:fullname_4: Pete McAllister
:initials_4: P.
:surname_4: McAllister
:affiliation_4: Metaswitch Networks
:email_4: pete.mcallister@metaswitch.com
:address_4: 100 Church Street + \
Enfield + \
United Kingdom + \
EN2 6BQ
:fullname_5: Anish Peter
:initials_5: A.
:surname_5: Peter
:affiliation_5: IP Infusion India
:email_5: anish.ietf@gmail.com
:address_5: Kundanahalli Main Road, Mahadevapura Post + \
Bangalore + \
India + \
RMZ Centennial, Block D 401

[abstract]
== Abstract
This document defines a YANG data model that can be used to configure and manage Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) devices.

[[status-of-memo]]
[numbered=false,removeInRFC=false,toc=exclude]
== Status of This Memo

This is an Internet Standards Track document.

This document is a product of the Internet Engineering Task Force (IETF). It represents the consensus of the IETF community. It has received public review and has been approved for publication by the Internet Engineering Steering Group (IESG). Further information on Internet Standards is available in Section 2 of RFC 7841.

Information about the current status of this document, any errata, and how to provide feedback on it may be obtained at  https://www.rfc-editor.org/info/rfc8652.

[[copyright]]
[numbered=false,removeInRFC=false,toc=exclude]
== Copyright Notice

Copyright (c) 2019 IETF Trust and the persons identified as the document authors. All rights reserved.

This document is subject to BCP 78 and the IETF Trust's Legal Provisions Relating to IETF Documents ( https://trustee.ietf.org/license-info) in effect on the date of publication of this document. Please review these documents carefully, as they describe your rights and restrictions with respect to this document. Code Components extracted from this document must include Simplified BSD License text as described in Section 4.e of the Trust Legal Provisions and are provided without warranty as described in the Simplified BSD License.

[[toc]]
[numbered=false,removeInRFC=false,toc=exclude]
== Table of Contents

[nobullet=true,spacing=compact]
* <<section-1,format=counter>>.  <<name-introduction,format=title: Introduction>>
[nobullet=true,spacing=compact]
** <<section-1.1,format=counter>>.  <<name-terminology,format=title: Terminology>>
** <<section-1.2,format=counter>>.  <<name-conventions-used-in-this-do,format=title: Conventions Used in This Document>>
** <<section-1.3,format=counter>>.  <<name-tree-diagrams,format=title: Tree Diagrams>>
** <<section-1.4,format=counter>>.  <<name-prefixes-in-data-node-names,format=title: Prefixes in Data Node Names>>
* <<section-2,format=counter>>.  <<name-design-of-the-data-model,format=title: Design of the Data Model>>
[nobullet=true,spacing=compact]
** <<section-2.1,format=counter>>.  <<name-scope-of-model,format=title: Scope of Model>>
[nobullet=true,spacing=compact]
*** <<section-2.1.1,format=counter>>.  <<name-parameters-not-covered-at-t,format=title: Parameters Not Covered at the Global Level>>
*** <<section-2.1.2,format=counter>>.  <<name-parameters-not-covered-at-th,format=title: Parameters Not Covered at the Interface Level>>
** <<section-2.2,format=counter>>.  <<name-optional-capabilities,format=title: Optional Capabilities>>
** <<section-2.3,format=counter>>.  <<name-position-of-address-family-,format=title: Position of Address Family in Hierarchy>>
* <<section-3,format=counter>>.  <<name-module-structure,format=title: Module Structure>>
[nobullet=true,spacing=compact]
** <<section-3.1,format=counter>>.  <<name-igmp-configuration-and-oper,format=title: IGMP Configuration and Operational State>>
** <<section-3.2,format=counter>>.  <<name-mld-configuration-and-opera,format=title: MLD Configuration and Operational State>>
** <<section-3.3,format=counter>>.  <<name-igmp-and-mld-actions,format=title: IGMP and MLD Actions>>
* <<section-4,format=counter>>.  <<name-igmp-and-mld-yang-module,format=title: IGMP and MLD YANG Module>>
* <<section-5,format=counter>>.  <<name-security-considerations,format=title: Security Considerations>>
* <<section-6,format=counter>>.  <<name-iana-considerations,format=title: IANA Considerations>>
* <<section-7,format=counter>>.  <<name-references,format=title: References>>
[nobullet=true,spacing=compact]
** <<section-7.1,format=counter>>.  <<name-normative-references,format=title: Normative References>>
** <<section-7.2,format=counter>>.  <<name-informative-references,format=title: Informative References>>
* <<section-appendix.a,format=none>><<name-acknowledgments,format=title: Acknowledgments>>
* <<section-appendix.b,format=none>><<name-contributors,format=title: Contributors>>
* <<section-appendix.c,format=none>><<name-authors-addresses,format=title: Authors' Addresses>>

[[s-1]]
[numbered=true,removeInRFC=false,toc=include]
== Introduction

YANG <<RFC6020,format=default>> <<RFC7950,format=default>> is a data definition language that was introduced to model the configuration and running state of a device managed using network management protocols such as NETCONF <<RFC6241,format=default>> or RESTCONF <<RFC8040,format=default>>. YANG is now also being used as a component of wider management interfaces, such as command-line interfaces (CLIs).

This document defines a YANG data model that can be used to configure and manage Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) devices. The protocol versions include IGMPv1 <<RFC1112,format=default>>, IGMPv2 <<RFC2236,format=default>>, IGMPv3 <<RFC3376,format=default>>, MLDv1 <<RFC2710,format=default>>, and MLDv2 <<RFC3810,format=default>>. The core features of the IGMP and MLD protocols are defined as required. Non-core features are defined as optional in the provided data model.

The YANG data model in this document conforms to the Network Management Datastore Architecture (NMDA) <<RFC8342,format=default>>.

[[s-1.1]]
[numbered=true,removeInRFC=false,toc=include]
=== Terminology

The terminology for describing YANG data models is found in <<RFC6020,format=default>> and <<RFC7950,format=default>>, including:

[nobullet=false,spacing=normal]
* augment
* data model
* data node
* identity
* module

The following abbreviations are used in this document and the defined model:

[indent=3,newline=false,spacing=normal]
IGMP::: Internet Group Management Protocol <<RFC3376,format=default>>.
MLD::: Multicast Listener Discovery <<RFC3810,format=default>>.
SSM::: Source-Specific Multicast service model <<RFC3569,format=default>><<RFC4607,format=default>>.

[[s-1.2]]
[numbered=true,removeInRFC=false,toc=include]
=== Conventions Used in This Document

The key words "[bcp14]#MUST#", "[bcp14]#MUST NOT#", "[bcp14]#REQUIRED#", "[bcp14]#SHALL#", "[bcp14]#SHALL NOT#", "[bcp14]#SHOULD#", "[bcp14]#SHOULD NOT#", "[bcp14]#RECOMMENDED#", "[bcp14]#NOT RECOMMENDED#", "[bcp14]#MAY#", and "[bcp14]#OPTIONAL#" in this document are to be interpreted as described in BCP 14 <<RFC2119,format=default>> <<RFC8174,format=default>> when, and only when, they appear in all capitals, as shown here.

[[s-1.2.a]]
[numbered=true,removeInRFC=false,toc=include]
=== Tree Diagrams

Tree diagrams used in this document follow the notation defined in <<RFC8340,format=default>>.

[[s-1.3]]
[numbered=true,removeInRFC=false,toc=include]
=== Prefixes in Data Node Names

In this document, names of data nodes, actions, and other data model objects are often used without a prefix, as long as it is clear from the context in which YANG module each name is defined. Otherwise, names are prefixed using the standard prefix associated with the corresponding YANG module, as shown in Table 1.

[[ref-prefixes-and-corresponding-yang-modules]]
.Prefixes and Corresponding YANG Modules
[align=center]
|===
h|Prefix | YANG module | Reference
|:--- | :--- | :---

|yang | ietf-yang-types | <<RFC6991,format=default>>
|inet | ietf-inet-types | <<RFC6991,format=default>>
|if | ietf-interfaces | <<RFC8343,format=default>>
|ip | ietf-ip | <<RFC8344,format=default>>
|rt | ietf-routing | <<RFC8349,format=default>>
|rt-types | ietf-routing-types | <<RFC8294,format=default>>
|acl | ietf-access-control-list | <<RFC8519,format=default>>
|===

[[s-2]]
[numbered=true,removeInRFC=false,toc=include]
== Design of the Data Model

[[s-2.1]]
[numbered=true,removeInRFC=false,toc=include]
=== Scope of Model

The model covers IGMPv1 <<RFC1112,format=default>>, IGMPv2 <<RFC2236,format=default>>, IGMPv3 <<RFC3376,format=default>>, MLDv1 <<RFC2710,format=default>>, and MLDv2 <<RFC3810,format=default>>.

This model does not cover other IGMP- and MLD-related protocols such as IGMP/MLD Proxy <<RFC4605,format=default>> or IGMP/MLD Snooping <<RFC4541,format=default>> etc., which will be specified in separate documents.

This model can be used to configure and manage various versions of IGMP and MLD protocols. The operational state data and statistics can be retrieved by this model. Even though no protocol-specific notifications are defined in this model, the subscription and push mechanism defined in <<RFC8639,format=default>> and <<RFC8641,format=default>> can be implemented by the user to subscribe to notifications on the data nodes in this model.

The model contains all the basic configuration parameters to operate the protocols listed above. Depending on the implementation choices, some systems may not allow some of the advanced parameters to be configurable. The occasionally implemented parameters are modeled as optional features in this model, while the rarely implemented parameters are not included in this model and left for augmentation. This model can be extended, and it has been structured in a way that such extensions can be conveniently made.

The protocol parameters covered in this model can been seen from the model structure described in <<s-3,format=default>>.

The protocol parameters that were considered but are not covered in this model are described in the following sections.

[[s-2.1.1]]
[numbered=true,removeInRFC=false,toc=include]
==== Parameters Not Covered at the Global Level

The configuration parameters and operational states not covered on an IGMP instance or an MLD instance are:

[nobullet=false,spacing=normal]
* Explicit tracking
* Maximum transmit rate
* Last member query count
* Other querier present time
* Send router alert
* Startup query interval
* Startup query count

[[s-2.1.2]]
[numbered=true,removeInRFC=false,toc=include]
==== Parameters Not Covered at the Interface Level

The configuration parameters and operational states not covered on an IGMP interface or an MLD interface are:

[nobullet=false,spacing=normal]
* Disable router alert check
* Drop IGMP version 1, IGMP version 2, or MLD version 1
* Last member query count
* Maximum number of sources
* Other querier present time
* Passive mode
* Promiscuous mode
* Query before immediate leave
* Send router alert

[[s-2.2]]
[numbered=true,removeInRFC=false,toc=include]
=== Optional Capabilities

This model is designed to represent the capabilities of IGMP and MLD devices with various specifications, including the basic capability subsets of the IGMP and MLD protocols. The main design goals of this document are that the basic capabilities described in the model are supported by any major now-existing implementation, and that the configuration of all implementations meeting the specifications is easy to express through some combination of the optional features in the model and simple vendor augmentations.

There is also value in widely supported features being standardized, to provide a standardized way to access these features, to save work for individual vendors, and so that mapping between different vendors' configuration is not needlessly complicated. Therefore, this model declares a number of features representing capabilities that not all deployed devices support.

The extensive use of feature declarations should also substantially simplify the capability negotiation process for a vendor's IGMP and MLD implementations.

On the other hand, operational state parameters are not so widely designated as features, as there are many cases where the defaulting of an operational state parameter would not cause any harm to the system, and it is much more likely that an implementation without native support for a piece of operational state would be able to derive a suitable value for a state variable that is not natively supported.

[[s-2.3]]
[numbered=true,removeInRFC=false,toc=include]
=== Position of Address Family in Hierarchy

The protocol IGMP only supports IPv4, while the protocol MLD only supports IPv6. The data model defined in this document can be used for both IPv4 and IPv6 address families.

This document defines IGMP and MLD as separate schema branches in the structure. The benefits are:

[nobullet=false,spacing=normal]
* The model can support IGMP (IPv4), MLD (IPv6), or both optionally and independently. Such flexibility cannot be achieved cleanly with a combined branch.
* The structure is consistent with other YANG data models such as RFC 8344, which uses separate branches for IPv4 and IPv6.
* The separate branches for IGMP and MLD can accommodate their differences better and cleaner. The two branches can better support different features and node types.

[[s-3]]
[numbered=true,removeInRFC=false,toc=include]
== Module Structure

This model augments the core routing data model specified in <<RFC8349,format=default>>.

[source,markers=false,yangtree]
----
      +--rw routing
         +--rw router-id?
         +--rw control-plane-protocols
         |  +--rw control-plane-protocol* [type name]
         |     +--rw type
         |     +--rw name
         |     +--rw igmp     <= Augmented by this Model
                     ...
         |     +--rw mld      <= Augmented by this Model
                     ...
----

The "igmp" container instantiates an IGMP protocol of version IGMPv1, IGMPv2, or IGMPv3. The "mld" container instantiates an MLD protocol of version MLDv1 or MLDv2.

The YANG data model defined in this document conforms to the Network Management Datastore Architecture (NMDA) <<RFC8342,format=default>>. The operational state data is combined with the associated configuration data in the same hierarchy <<RFC8407,format=default>>.

A configuration data node is marked as mandatory only when its value must be provided by the user. Where nodes are not essential to protocol operation, they are marked as optional. Some other nodes are essential but have a default specified, so that they are also optional and need not be configured explicitly.

[[s-3.1]]
[numbered=true,removeInRFC=false,toc=include]
=== IGMP Configuration and Operational State

The IGMP data is modeled as a schema subtree augmenting the "control-plane-protocol" data node under "/rt:routing/rt:control-plane-protocols" in the module ietf-routing, following the convention described in <<RFC8349,format=default>>. The augmentation to the module ietf-routing allows this model to support multiple instances of IGMP, but a restriction [bcp14]#MAY# be added depending on the implementation and the device. The identity "igmp" is derived from the "rt:control-plane-protocol" base identity and indicates that a control-plane-protocol instance is IGMP.

The IGMP subtree is a three-level hierarchy structure as listed below:

[indent=3,newline=false,spacing=normal]
Global level::: Including IGMP configuration and operational state attributes for the entire IGMP protocol instance in this router.
Interface-global level::: Including configuration data nodes that are applicable to all the interfaces whose corresponding nodes are not defined or not configured at the interface level. For such a node at the interface level, the system uses the same value of the corresponding node at the interface-global level.
Interface level::: Including IGMP configuration and operational state attributes specific to the given interface. For a configuration node at the interface level, there may exist a corresponding configuration node with the same name at the interface-global level. The value configured on a node at the interface level overrides the value configured on the corresponding node at the interface-global level.

[source,markers=false,yangtree]
----
  augment /rt:routing/rt:control-plane-protocols
            /rt:control-plane-protocol:
    +--rw igmp {feature-igmp}?
       +--rw global
       |  +--rw enabled?         boolean {global-admin-enable}?
       |  +--rw max-entries?     uint32 {global-max-entries}?
       |  +--rw max-groups?      uint32 {global-max-groups}?
       |  +--ro entries-count?   uint32
       |  +--ro groups-count?    uint32
       |  +--ro statistics
       |     +--ro discontinuity-time?   yang:date-and-time
       |     +--ro error
       |     |  +--ro total?       yang:counter64
       |     |  +--ro query?       yang:counter64
       |     |  +--ro report?      yang:counter64
       |     |  +--ro leave?       yang:counter64
       |     |  +--ro checksum?    yang:counter64
       |     |  +--ro too-short?   yang:counter64
       |     +--ro received
       |     |  +--ro total?    yang:counter64
       |     |  +--ro query?    yang:counter64
       |     |  +--ro report?   yang:counter64
       |     |  +--ro leave?    yang:counter64
       |     +--ro sent
       |        +--ro total?    yang:counter64
       |        +--ro query?    yang:counter64
       |        +--ro report?   yang:counter64
       |        +--ro leave?    yang:counter64
       +--rw interfaces
          +--rw last-member-query-interval?   uint16
          +--rw query-interval?               uint16
          +--rw query-max-response-time?      uint16
          +--rw require-router-alert?         boolean
          |       {intf-require-router-alert}?
          +--rw robustness-variable?          uint8
          +--rw version?                      uint8
          +--rw max-groups-per-interface?     uint32
          |       {intf-max-groups}?
          +--rw interface* [interface-name]
             +--rw interface-name                if:interface-ref
             +--rw last-member-query-interval?   uint16
             +--rw query-interval?               uint16
             +--rw query-max-response-time?      uint16
             +--rw require-router-alert?         boolean
             |       {intf-require-router-alert}?
             +--rw robustness-variable?          uint8
             +--rw version?                      uint8
             +--rw enabled?                      boolean
             |       {intf-admin-enable}?
             +--rw group-policy?
             |       -> /acl:acls/acl/name
             +--rw immediate-leave?              empty
             |       {intf-immediate-leave}?
             +--rw max-groups?                   uint32
             |       {intf-max-groups}?
             +--rw max-group-sources?            uint32
             |       {intf-max-group-sources}?
             +--rw source-policy?
             |       -> /acl:acls/acl/name {intf-source-policy}?
             +--rw verify-source-subnet?         empty
             |       {intf-verify-source-subnet}?
             +--rw explicit-tracking?            empty
             |       {intf-explicit-tracking}?
             +--rw lite-exclude-filter?          empty
             |       {intf-lite-exclude-filter}?
             +--rw join-group*
             |       rt-types:ipv4-multicast-group-address
             |       {intf-join-group}?
             +--rw ssm-map*
             |       [ssm-map-source-addr ssm-map-group-policy]
             |       {intf-ssm-map}?
             |  +--rw ssm-map-source-addr     ssm-map-ipv4-addr-type
             |  +--rw ssm-map-group-policy    string
             +--rw static-group* [group-addr source-addr]
             |       {intf-static-group}?
             |  +--rw group-addr
             |  |       rt-types:ipv4-multicast-group-address
             |  +--rw source-addr
             |          rt-types:ipv4-multicast-source-address
             +--ro oper-status                   enumeration
             +--ro querier                       inet:ipv4-address
             +--ro joined-group*
             |       rt-types:ipv4-multicast-group-address
             |       {intf-join-group}?
             +--ro group* [group-address]
                +--ro group-address
                |       rt-types:ipv4-multicast-group-address
                +--ro expire           uint32
                +--ro filter-mode      enumeration
                +--ro up-time          uint32
                +--ro last-reporter?   inet:ipv4-address
                +--ro source* [source-address]
                   +--ro source-address    inet:ipv4-address
                   +--ro expire            uint32
                   +--ro up-time           uint32
                   +--ro host-count?       uint32
                   |       {intf-explicit-tracking}?
                   +--ro last-reporter?    inet:ipv4-address
                   +--ro host* [host-address]
                           {intf-explicit-tracking}?
                      +--ro host-address        inet:ipv4-address
                      +--ro host-filter-mode    enumeration
----

[[s-3.2]]
[numbered=true,removeInRFC=false,toc=include]
=== MLD Configuration and Operational State

The MLD data is modeled as a schema subtree augmenting the "control-plane-protocol" data node under "/rt:routing/rt:control-plane-protocols" in the module ietf-routing, following the convention described in <<RFC8349,format=default>>. The augmentation to the module ietf-routing allows this model to support multiple instances of MLD, but a restriction [bcp14]#MAY# be added depending on the implementation and the device. The identity "mld" is derived from the "rt:control-plane-protocol" base identity and indicates that a control-plane-protocol instance is MLD.

The MLD subtree is a three-level hierarchy structure as listed below:

[indent=3,newline=false,spacing=normal]
Global level::: Including MLD configuration and operational state attributes for the entire MLD protocol instance in this router.
Interface-global level::: Including configuration data nodes that are applicable to all the interfaces whose corresponding nodes are not defined or not configured at the interface level. For such a node at the interface level, the system uses the same value of the corresponding node at the interface-global level.
Interface level::: Including MLD configuration and operational state attributes specific to the given interface. For a configuration node at the interface level, there may exist a corresponding configuration node with the same name at the interface-global level. The value configured on a node at the interface level overrides the value configured on the corresponding node at the interface-global level.

[source,markers=false,yangtree]
----
  augment /rt:routing/rt:control-plane-protocols
            /rt:control-plane-protocol:
    +--rw mld {feature-mld}?
       +--rw global
       |  +--rw enabled?         boolean {global-admin-enable}?
       |  +--rw max-entries?     uint32 {global-max-entries}?
       |  +--rw max-groups?      uint32 {global-max-groups}?
       |  +--ro entries-count?   uint32
       |  +--ro groups-count?    uint32
       |  +--ro statistics
       |     +--ro discontinuity-time?   yang:date-and-time
       |     +--ro error
       |     |  +--ro total?       yang:counter64
       |     |  +--ro query?       yang:counter64
       |     |  +--ro report?      yang:counter64
       |     |  +--ro leave?       yang:counter64
       |     |  +--ro checksum?    yang:counter64
       |     |  +--ro too-short?   yang:counter64
       |     +--ro received
       |     |  +--ro total?    yang:counter64
       |     |  +--ro query?    yang:counter64
       |     |  +--ro report?   yang:counter64
       |     |  +--ro leave?    yang:counter64
       |     +--ro sent
       |        +--ro total?    yang:counter64
       |        +--ro query?    yang:counter64
       |        +--ro report?   yang:counter64
       |        +--ro leave?    yang:counter64
       +--rw interfaces
          +--rw last-member-query-interval?   uint16
          +--rw query-interval?               uint16
          +--rw query-max-response-time?      uint16
          +--rw require-router-alert?         boolean
          |       {intf-require-router-alert}?
          +--rw robustness-variable?          uint8
          +--rw version?                      uint8
          +--rw max-groups-per-interface?     uint32
          |       {intf-max-groups}?
          +--rw interface* [interface-name]
             +--rw interface-name                if:interface-ref
             +--rw last-member-query-interval?   uint16
             +--rw query-interval?               uint16
             +--rw query-max-response-time?      uint16
             +--rw require-router-alert?         boolean
             |       {intf-require-router-alert}?
             +--rw robustness-variable?          uint8
             +--rw version?                      uint8
             +--rw enabled?                      boolean
             |       {intf-admin-enable}?
             +--rw group-policy?
             |       -> /acl:acls/acl/name
             +--rw immediate-leave?              empty
             |       {intf-immediate-leave}?
             +--rw max-groups?                   uint32
             |       {intf-max-groups}?
             +--rw max-group-sources?            uint32
             |       {intf-max-group-sources}?
             +--rw source-policy?
             |       -> /acl:acls/acl/name {intf-source-policy}?
             +--rw verify-source-subnet?         empty
             |       {intf-verify-source-subnet}?
             +--rw explicit-tracking?            empty
             |       {intf-explicit-tracking}?
             +--rw lite-exclude-filter?          empty
             |       {intf-lite-exclude-filter}?
             +--rw join-group*
             |       rt-types:ipv6-multicast-group-address
             |       {intf-join-group}?
             +--rw ssm-map*
             |       [ssm-map-source-addr ssm-map-group-policy]
             |       {intf-ssm-map}?
             |  +--rw ssm-map-source-addr     ssm-map-ipv6-addr-type
             |  +--rw ssm-map-group-policy    string
             +--rw static-group* [group-addr source-addr]
             |       {intf-static-group}?
             |  +--rw group-addr
             |  |       rt-types:ipv6-multicast-group-address
             |  +--rw source-addr
             |          rt-types:ipv6-multicast-source-address
             +--ro oper-status                   enumeration
             +--ro querier                       inet:ipv6-address
             +--ro joined-group*
             |       rt-types:ipv6-multicast-group-address
             |       {intf-join-group}?
             +--ro group* [group-address]
                +--ro group-address
                |       rt-types:ipv6-multicast-group-address
                +--ro expire           uint32
                +--ro filter-mode      enumeration
                +--ro up-time          uint32
                +--ro last-reporter?   inet:ipv6-address
                +--ro source* [source-address]
                   +--ro source-address    inet:ipv6-address
                   +--ro expire            uint32
                   +--ro up-time           uint32
                   +--ro host-count?       uint32
                   |       {intf-explicit-tracking}?
                   +--ro last-reporter?    inet:ipv6-address
                   +--ro host* [host-address]
                           {intf-explicit-tracking}?
                      +--ro host-address        inet:ipv6-address
                      +--ro host-filter-mode    enumeration
----

[[s-3.3]]
[numbered=true,removeInRFC=false,toc=include]
=== IGMP and MLD Actions

IGMP and MLD each have one action that clears the group membership cache entries for that protocol.

[source,markers=false,yangtree]
----
  augment /rt:routing/rt:control-plane-protocols
            /rt:control-plane-protocol:
    +--rw igmp {feature-igmp}?
       +---x clear-groups {action-clear-groups}?
          +---w input
             +---w (interface)
             |  +--:(name)
             |  |  +---w interface-name?   leafref
             |  +--:(all)
             |     +---w all-interfaces?   empty
             +---w group-address           union
             +---w source-address
                     rt-types:ipv4-multicast-source-address

  augment /rt:routing/rt:control-plane-protocols
            /rt:control-plane-protocol:
    +--rw mld {feature-mld}?
       +---x clear-groups {action-clear-groups}?
          +---w input
             +---w (interface)
             |  +--:(name)
             |  |  +---w interface-name?   leafref
             |  +--:(all)
             |     +---w all-interfaces?   empty
             +---w group-address?          union
             +---w source-address?
                     rt-types:ipv6-multicast-source-address
----

[[s-4]]
[numbered=true,removeInRFC=false,toc=include]
== IGMP and MLD YANG Module

This module references <<RFC1112,format=default>>, <<RFC2236,format=default>>, <<RFC2710,format=default>>, <<RFC3376,format=default>>, <<RFC3810,format=default>>, <<RFC5790,format=default>>, <<RFC6636,format=default>>, <<RFC6991,format=default>>, <<RFC8294,format=default>>, <<RFC8343,format=default>>, <<RFC8344,format=default>>, <<RFC8349,format=default>>, and <<RFC8519,format=default>>.

[source,markers=true,filename=ietf-igmp-mld@2019-11-01.yang,yang]
----
module ietf-igmp-mld {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:ietf-igmp-mld";
  prefix igmp-mld;

  import ietf-inet-types {
    prefix inet;
    reference
      "RFC 6991: Common YANG Data Types";
  }
  import ietf-yang-types {
    prefix yang;
    reference
      "RFC 6991: Common YANG Data Types";
  }
  import ietf-routing-types {
    prefix rt-types;
    reference
      "RFC 8294: Common YANG Data Types for the Routing Area";
  }
  import ietf-access-control-list {
    prefix acl;
    reference
      "RFC 8519: YANG Data Model for Network Access Control Lists
       (ACLs)";
  }
  import ietf-routing {
    prefix rt;
    reference
      "RFC 8349: A YANG Data Model for Routing Management (NMDA
       Version)";
  }
  import ietf-interfaces {
    prefix if;
    reference
      "RFC 8343: A YANG Data Model for Interface Management";
  }
  import ietf-ip {
    prefix ip;
    reference
      "RFC 8344: A YANG Data Model for IP Management";
  }

  organization
    "IETF PIM Working Group";
  contact
    "WG Web:   <http://datatracker.ietf.org/wg/pim/>
     WG List:  <mailto:pim@ietf.org>

     Editor:   Xufeng Liu
               <mailto:xufeng.liu.ietf@gmail.com>

     Editor:   Feng Guo
               <mailto:guofeng@huawei.com>

     Editor:   Mahesh Sivakumar
               <mailto:sivakumar.mahesh@gmail.com>

     Editor:   Pete McAllister
               <mailto:pete.mcallister@metaswitch.com>

     Editor:   Anish Peter
               <mailto:anish.ietf@gmail.com>";
  description
    "The module defines the configuration and operational state for
     the Internet Group Management Protocol (IGMP) and Multicast
     Listener Discovery (MLD) protocols.

     The key words 'MUST', 'MUST NOT', 'REQUIRED', 'SHALL', 'SHALL
     NOT', 'SHOULD', 'SHOULD NOT', 'RECOMMENDED', 'NOT RECOMMENDED',
     'MAY', and 'OPTIONAL' in this document are to be interpreted as
     described in BCP 14 (RFC 2119) (RFC 8174) when, and only when,
     they appear in all capitals, as shown here.

     Copyright (c) 2019 IETF Trust and the persons identified as
     authors of the code.  All rights reserved.

     Redistribution and use in source and binary forms, with or
     without modification, is permitted pursuant to, and subject to
     the license terms contained in, the Simplified BSD License set
     forth in Section 4.c of the IETF Trust's Legal Provisions
     Relating to IETF Documents
     (http://trustee.ietf.org/license-info).

     This version of this YANG module is part of RFC 8652; see the
     RFC itself for full legal notices.";

  revision 2019-11-01 {
    description
      "Initial revision.";
    reference
      "RFC 8652: A YANG Data Model for the Internet Group Management
       Protocol (IGMP) and Multicast Listener Discovery (MLD)";
  }

  /*
   * Features
   */

  feature feature-igmp {
    description
      "Support IGMP protocol for IPv4 group membership record.";
  }

  feature feature-mld {
    description
      "Support MLD protocol for IPv6 group membership record.";
  }

  feature global-admin-enable {
    description
      "Support global configuration to enable or disable protocol.";
  }

  feature global-max-entries {
    description
      "Support configuration of global max-entries.";
  }

  feature global-max-groups {
    description
      "Support configuration of global max-groups.";
  }

  feature interface-global-config {
    description
      "Support global configuration applied for all interfaces.";
  }

  feature intf-admin-enable {
    description
      "Support configuration of interface administrative enabling.";
  }

  feature intf-immediate-leave {
    description
      "Support configuration of interface immediate-leave.";
  }

  feature intf-join-group {
    description
      "Support configuration of interface join-group.";
  }

  feature intf-max-groups {
    description
      "Support configuration of interface max-groups.";
  }

  feature intf-max-group-sources {
    description
      "Support configuration of interface max-group-sources.";
  }

  feature intf-require-router-alert {
    description
      "Support configuration of interface require-router-alert.";
  }

  feature intf-source-policy {
    description
      "Support configuration of interface source policy.";
  }

  feature intf-ssm-map {
    description
      "Support configuration of interface ssm-map.";
  }

  feature intf-static-group {
    description
      "Support configuration of interface static-group.";
  }

  feature intf-verify-source-subnet {
    description
      "Support configuration of interface verify-source-subnet.";
  }

  feature intf-explicit-tracking {
    description
      "Support configuration of interface explicit-tracking hosts.";
  }

  feature intf-lite-exclude-filter {
    description
      "Support configuration of interface lite-exclude-filter.";
  }

  feature per-interface-config {
    description
      "Support per-interface configuration.";
  }

  feature action-clear-groups {
    description
      "Support actions to clear groups.";
  }

  /*
   * Typedefs
   */

  typedef ssm-map-ipv4-addr-type {
    type union {
      type enumeration {
        enum policy {
          description
            "Source address is specified in SSM map policy.";
        }
      }
      type inet:ipv4-address;
    }
    description
      "Multicast source IP address type for SSM map.";
  }
  // source-ipv4-addr-type

  typedef ssm-map-ipv6-addr-type {
    type union {
      type enumeration {
        enum policy {
          description
            "Source address is specified in SSM map policy.";
        }
      }
      type inet:ipv6-address;
    }
    description
      "Multicast source IP address type for SSM map.";
  }
  // source-ipv6-addr-type

  /*
   * Identities
   */

  identity igmp {
    if-feature "feature-igmp";
    base rt:control-plane-protocol;
    description
      "IGMP protocol.";
    reference
      "RFC 3376: Internet Group Management Protocol, Version 3";
  }

  identity mld {
    if-feature "feature-mld";
    base rt:control-plane-protocol;
    description
      "MLD protocol.";
    reference
      "RFC 3810: Multicast Listener Discovery Version 2 (MLDv2) for
       IPv6";
  }

  /*
   * Groupings
   */

  grouping global-config-attributes {
    description
      "This grouping is used in either IGMP schema or MLD schema.
       When used in IGMP schema, this grouping contains the global
       configuration for IGMP;
       when used in MLD schema, this grouping contains the global
       configuration for MLD.";
    leaf enabled {
      if-feature "global-admin-enable";
      type boolean;
      default "true";
      description
        "When this grouping is used for IGMP, this leaf indicates
         whether IGMP is enabled ('true') or disabled ('false')
         in the routing instance.
         When this grouping is used for MLD, this leaf indicates
         whether MLD is enabled ('true') or disabled ('false')
         in the routing instance.";
    }
    leaf max-entries {
      if-feature "global-max-entries";
      type uint32;
      description
        "When this grouping is used for IGMP, this leaf indicates
         the maximum number of entries in the IGMP instance.
         When this grouping is used for MLD, this leaf indicates
         the maximum number of entries in the MLD instance.
         If this leaf is not specified, the number of entries is not
         limited.";
    }
    leaf max-groups {
      if-feature "global-max-groups";
      type uint32;
      description
        "When this grouping is used for IGMP, this leaf indicates
         the maximum number of groups in the IGMP instance.
         When this grouping is used for MLD, this leaf indicates
         the maximum number of groups in the MLD instance.
         If this leaf is not specified, the number of groups is not
         limited.";
    }
  }
  // global-config-attributes

  grouping global-state-attributes {
    description
      "This grouping is used in either IGMP schema or MLD schema.
       When used in IGMP schema, this grouping contains the global
       IGMP state attributes;
       when used in MLD schema, this grouping contains the global
       MLD state attributes.";
    leaf entries-count {
      type uint32;
      config false;
      description
        "When this grouping is used for IGMP, this leaf indicates
         the number of entries in the IGMP instance.
         When this grouping is used for MLD, this leaf indicates
         the number of entries in the MLD instance.";
    }
    leaf groups-count {
      type uint32;
      config false;
      description
        "When this grouping is used for IGMP, this leaf indicates
         the number of existing groups in the IGMP instance.
         When this grouping is used for MLD, this leaf indicates
         the number of existing groups in the MLD instance.";
    }
    container statistics {
      config false;
      description
        "When this grouping is used for IGMP, this container contains
         the statistics for the IGMP instance.
         When this grouping is used for MLD, this leaf indicates
         the statistics for the MLD instance.";
      leaf discontinuity-time {
        type yang:date-and-time;
        description
          "The time on the most recent occasion at which any one
           or more of the statistic counters suffered a
           discontinuity.  If no such discontinuities have occurred
           since the last re-initialization of the local
           management subsystem, then this node contains the time
           the local management subsystem re-initialized itself.";
      }
      container error {
        description
          "Statistics of errors.";
        uses global-statistics-error;
      }
      container received {
        description
          "Statistics of received messages.";
        uses global-statistics-sent-received;
      }
      container sent {
        description
          "Statistics of sent messages.";
        uses global-statistics-sent-received;
      }
    }
    // statistics
  }
  // global-state-attributes

  grouping global-statistics-error {
    description
      "A grouping defining statistics attributes for errors.";
    uses global-statistics-sent-received;
    leaf checksum {
      type yang:counter64;
      description
        "The number of checksum errors.";
    }
    leaf too-short {
      type yang:counter64;
      description
        "The number of messages that are too short.";
    }
  }
  // global-statistics-error

  grouping global-statistics-sent-received {
    description
      "A grouping defining statistics attributes.";
    leaf total {
      type yang:counter64;
      description
        "The number of total messages.";
    }
    leaf query {
      type yang:counter64;
      description
        "The number of query messages.";
    }
    leaf report {
      type yang:counter64;
      description
        "The number of report messages.";
    }
    leaf leave {
      type yang:counter64;
      description
        "The number of leave messages.";
    }
  }
  // global-statistics-sent-received

  grouping interface-global-config-attributes {
    description
      "Configuration attributes applied to the interface-global level
       whose per-interface attributes are not configured.";
    leaf max-groups-per-interface {
      if-feature "intf-max-groups";
      type uint32;
      description
        "The maximum number of groups associated with each interface.
         If this leaf is not specified, the number of groups is not
         limited.";
    }
  }
  // interface-global-config-attributes

  grouping interface-common-config-attributes {
    description
      "Configuration attributes applied to both the interface-global
       level and interface level.";
    leaf last-member-query-interval {
      type uint16 {
        range "1..1023";
      }
      units "seconds";
      description
        "When used in IGMP schema, this leaf indicates the Last
         Member Query Interval, which may be tuned to modify the
         leave latency of the network;
         when used in MLD schema, this leaf indicates the Last
         Listener Query Interval, which may be tuned to modify the
         leave latency of the network.
         This leaf is not applicable for version 1 of the IGMP.  For
         version 2 and version 3 of the IGMP, and for all versions of
         the MLD, the default value of this leaf is 1.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "Section 8.8 of RFC 2236: Internet Group Management Protocol,
         Version 2.
         Section 8.8 of RFC 3376: Internet Group Management Protocol,
         Version 3.
         Section 7.8 of RFC 2710: Multicast Listener Discovery (MLD)
         for IPv6.
         Section 9.8 of RFC 3810: Multicast Listener Discovery
         Version 2 (MLDv2) for IPv6.";
    }
    leaf query-interval {
      type uint16 {
        range "1..31744";
      }
      units "seconds";
      description
        "The Query Interval is the interval between General Queries
         sent by the Querier.  In RFC 3376, the Querier's Query
         Interval (QQI) is represented from the Querier's Query
         Interval Code (QQIC) in query message as follows:
         If QQIC < 128, QQI = QQIC.
         If QQIC >= 128, QQIC represents a floating-point value as
         follows:
          0 1 2 3 4 5 6 7
         +-+-+-+-+-+-+-+-+
         |1| exp | mant  |
         +-+-+-+-+-+-+-+-+
         QQI = (mant | 0x10) << (exp + 3).
         The maximum value of QQI is 31744.
         The default value is 125.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "Sections 4.1.7, 8.2, and 8.14.2 of RFC 3376: Internet Group
         Management Protocol, Version 3";
    }
    leaf query-max-response-time {
      type uint16 {
        range "1..1023";
      }
      units "seconds";
      description
        "Query maximum response time specifies the maximum time
         allowed before sending a responding report.
         The default value is 10.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "Sections 4.1.1, 8.3, and 8.14.3 of RFC 3376: Internet Group
         Management Protocol, Version 3";
    }
    leaf require-router-alert {
      if-feature "intf-require-router-alert";
      type boolean;
      description
        "Protocol packets should contain the router alert IP option.
         When this leaf is not configured, the server uses the
         following rules to determine the operational value of this
         leaf:
         if this grouping is used in IGMP schema and the value of the
         leaf 'version' is 1, the value 'false' is operationally used
         by the server;
         if this grouping is used in IGMP schema and the value of the
         leaf 'version' is 2 or 3, the value 'true' is operationally
         used by the server;
         if this grouping is used in MLD schema, the value 'true' is
         operationally used by the server.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
    }
    leaf robustness-variable {
      type uint8 {
        range "1..7";
      }
      description
        "The Querier's Robustness Variable allows tuning for the
         expected packet loss on a network.
         The default value is 2.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "Sections 4.1.6, 8.1, and 8.14.1 of RFC 3376: Internet Group
         Management Protocol, Version 3";
    }
  }
  // interface-common-config-attributes

  grouping interface-common-config-attributes-igmp {
    description
      "Configuration attributes applied to both the interface-global
       level and interface level for IGMP.";
    uses interface-common-config-attributes;
    leaf version {
      type uint8 {
        range "1..3";
      }
      description
        "IGMP version.
         The default value is 2.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "RFC 1112: Host Extensions for IP Multicasting,
         RFC 2236: Internet Group Management Protocol, Version 2,
         RFC 3376: Internet Group Management Protocol, Version 3.";
    }
  }

  grouping interface-common-config-attributes-mld {
    description
      "Configuration attributes applied to both the interface-global
       level and interface level for MLD.";
    uses interface-common-config-attributes;
    leaf version {
      type uint8 {
        range "1..2";
      }
      description
        "MLD version.
         The default value is 2.
         This leaf may be configured at the interface level or the
         interface-global level, with precedence given to the value
         at the interface level.  If the leaf is not configured at
         either level, the default value is used.";
      reference
        "RFC 2710: Multicast Listener Discovery (MLD) for IPv6,
         RFC 3810: Multicast Listener Discovery Version 2 (MLDv2)
         for IPv6.";
    }
  }

  grouping interfaces-config-attributes-igmp {
    description
      "Configuration attributes applied to the interface-global
       level for IGMP.";
    uses interface-common-config-attributes-igmp;
    uses interface-global-config-attributes;
  }

  grouping interfaces-config-attributes-mld {
    description
      "Configuration attributes applied to the interface-global
       level for MLD.";
    uses interface-common-config-attributes-mld;
    uses interface-global-config-attributes;
  }

  grouping interface-level-config-attributes {
    description
      "This grouping is used in either IGMP schema or MLD schema.
       When used in IGMP schema, this grouping contains the IGMP
       configuration attributes that are defined at the interface
       level but are not defined at the interface-global level;
       when used in MLD schema, this grouping contains the MLD
       configuration attributes that are defined at the interface
       level but are not defined at the interface-global level.";
    leaf enabled {
      if-feature "intf-admin-enable";
      type boolean;
      default "true";
      description
        "When this grouping is used for IGMP, this leaf indicates
         whether IGMP is enabled ('true') or disabled ('false')
         on the interface.
         When this grouping is used for MLD, this leaf indicates
         whether MLD is enabled ('true') or disabled ('false')
         on the interface.";
    }
    leaf group-policy {
      type leafref {
        path "/acl:acls/acl:acl/acl:name";
      }
      description
        "When this grouping is used for IGMP, this leaf specifies
         the name of the access policy used to filter the
         IGMP membership.
         When this grouping is used for MLD, this leaf specifies
         the name of the access policy used to filter the
         MLD membership.
         The value space of this leaf is restricted to the existing
         policy instances defined by the referenced schema in
         RFC 8519.
         As specified by RFC 8519, the length of the name is between
         1 and 64; a device MAY further restrict the length of this
         name; space and special characters are not allowed.
         If this leaf is not specified, no policy is applied, and
         all packets received from this interface are accepted.";
      reference
        "RFC 8519: YANG Data Model for Network Access Control Lists
         (ACLs)";
    }
    leaf immediate-leave {
      if-feature "intf-immediate-leave";
      type empty;
      description
        "When this grouping is used for IGMP, the presence of this
         leaf requests IGMP to perform an immediate leave upon
         receiving an IGMPv2 leave message.
         If the router is IGMP-enabled, it sends an IGMP last member
         query with a last member query response time.  However, the
         router does not wait for the response time before it prunes
         the group.
         When this grouping is used for MLD, the presence of this
         leaf requests MLD to perform an immediate leave upon
         receiving an MLDv1 leave message.
         If the router is MLD-enabled, it sends an MLD last member
         query with a last member query response time.  However, the
         router does not wait for the response time before it prunes
         the group.";
    }
    leaf max-groups {
      if-feature "intf-max-groups";
      type uint32;
      description
        "When this grouping is used for IGMP, this leaf indicates
         the maximum number of groups associated with the IGMP
         interface.
         When this grouping is used for MLD, this leaf indicates
         the maximum number of groups associated with the MLD
         interface.
         If this leaf is not specified, the number of groups is not
         limited.";
    }
    leaf max-group-sources {
      if-feature "intf-max-group-sources";
      type uint32;
      description
        "The maximum number of group sources.
         If this leaf is not specified, the number of group sources
         is not limited.";
    }
    leaf source-policy {
      if-feature "intf-source-policy";
      type leafref {
        path "/acl:acls/acl:acl/acl:name";
      }
      description
        "Name of the access policy used to filter sources.
         The value space of this leaf is restricted to the existing
         policy instances defined by the referenced schema in
         RFC 8519.
         As specified by RFC 8519, the length of the name is between
         1 and 64; a device MAY further restrict the length of this
         name; space and special characters are not allowed.
         If this leaf is not specified, no policy is applied, and
         all packets received from this interface are accepted.";
    }
    leaf verify-source-subnet {
      if-feature "intf-verify-source-subnet";
      type empty;
      description
        "If present, the interface accepts packets with matching
         source IP subnet only.";
    }
    leaf explicit-tracking {
      if-feature "intf-explicit-tracking";
      type empty;
      description
        "When this grouping is used for IGMP, the presence of this
         leaf enables an IGMP-based explicit membership tracking
         function for multicast routers and IGMP proxy devices
         supporting IGMPv3.
         When this grouping is used for MLD, the presence of this
         leaf enables an MLD-based explicit membership tracking
         function for multicast routers and MLD proxy devices
         supporting MLDv2.
         The explicit membership tracking function contributes to
         saving network resources and shortening leave latency.";
      reference
        "Section 3 of RFC 6636: Tuning the Behavior of the Internet
         Group Management Protocol (IGMP) and Multicast Listener
         Discovery (MLD) for Routers in Mobile and Wireless
         Networks";
    }
    leaf lite-exclude-filter {
      if-feature "intf-lite-exclude-filter";
      type empty;
      description
        "When this grouping is used for IGMP, the presence of this
         leaf enables the support of the simplified EXCLUDE filter
         in the Lightweight IGMPv3 protocol, which simplifies the
         standard versions of IGMPv3.
         When this grouping is used for MLD, the presence of this
         leaf enables the support of the simplified EXCLUDE filter
         in the Lightweight MLDv2 protocol, which simplifies the
         standard versions of MLDv2.";
      reference
        "RFC 5790: Lightweight Internet Group Management Protocol
         Version 3 (IGMPv3) and Multicast Listener Discovery
         Version 2 (MLDv2) Protocols";
    }
  }
  // interface-level-config-attributes

  grouping interface-config-attributes-igmp {
    description
      "Per-interface configuration attributes for IGMP.";
    uses interface-common-config-attributes-igmp;
    uses interface-level-config-attributes;
    leaf-list join-group {
      if-feature "intf-join-group";
      type rt-types:ipv4-multicast-group-address;
      description
        "The router joins this multicast group on the interface.";
    }
    list ssm-map {
      if-feature "intf-ssm-map";
      key "ssm-map-source-addr ssm-map-group-policy";
      description
        "The policy for (*,G) mapping to (S,G).";
      leaf ssm-map-source-addr {
        type ssm-map-ipv4-addr-type;
        description
          "Multicast source IPv4 address.";
      }
      leaf ssm-map-group-policy {
        type string;
        description
          "Name of the policy used to define ssm-map rules.
           A device can restrict the length
           and value of this name, possibly space and special
           characters are not allowed.";
      }
    }
    list static-group {
      if-feature "intf-static-group";
      key "group-addr source-addr";
      description
        "A static multicast route, (*,G) or (S,G).
         The version of IGMP must be 3 to support (S,G).";
      leaf group-addr {
        type rt-types:ipv4-multicast-group-address;
        description
          "Multicast group IPv4 address.";
      }
      leaf source-addr {
        type rt-types:ipv4-multicast-source-address;
        description
          "Multicast source IPv4 address.";
      }
    }
  }
  // interface-config-attributes-igmp

  grouping interface-config-attributes-mld {
    description
      "Per-interface configuration attributes for MLD.";
    uses interface-common-config-attributes-mld;
    uses interface-level-config-attributes;
    leaf-list join-group {
      if-feature "intf-join-group";
      type rt-types:ipv6-multicast-group-address;
      description
        "The router joins this multicast group on the interface.";
    }
    list ssm-map {
      if-feature "intf-ssm-map";
      key "ssm-map-source-addr ssm-map-group-policy";
      description
        "The policy for (*,G) mapping to (S,G).";
      leaf ssm-map-source-addr {
        type ssm-map-ipv6-addr-type;
        description
          "Multicast source IPv6 address.";
      }
      leaf ssm-map-group-policy {
        type string;
        description
          "Name of the policy used to define ssm-map rules.
           A device can restrict the length
           and value of this name, possibly space and special
           characters are not allowed.";
      }
    }
    list static-group {
      if-feature "intf-static-group";
      key "group-addr source-addr";
      description
        "A static multicast route, (*,G) or (S,G).
         The version of MLD must be 2 to support (S,G).";
      leaf group-addr {
        type rt-types:ipv6-multicast-group-address;
        description
          "Multicast group IPv6 address.";
      }
      leaf source-addr {
        type rt-types:ipv6-multicast-source-address;
        description
          "Multicast source IPv6 address.";
      }
    }
  }
  // interface-config-attributes-mld

  grouping interface-state-attributes {
    description
      "Per-interface state attributes for both IGMP and MLD.";
    leaf oper-status {
      type enumeration {
        enum up {
          description
            "Ready to pass packets.";
        }
        enum down {
          description
            "The interface does not pass any packets.";
        }
      }
      config false;
      mandatory true;
      description
        "Indicates whether the operational state of the interface
         is up or down.";
    }
  }
  // interface-state-attributes

  grouping interface-state-attributes-igmp {
    description
      "Per-interface state attributes for IGMP.";
    uses interface-state-attributes;
    leaf querier {
      type inet:ipv4-address;
      config false;
      mandatory true;
      description
        "The querier address in the subnet.";
    }
    leaf-list joined-group {
      if-feature "intf-join-group";
      type rt-types:ipv4-multicast-group-address;
      config false;
      description
        "The routers that joined this multicast group.";
    }
    list group {
      key "group-address";
      config false;
      description
        "Multicast group membership information
         that joined on the interface.";
      leaf group-address {
        type rt-types:ipv4-multicast-group-address;
        description
          "Multicast group address.";
      }
      uses interface-state-group-attributes;
      leaf last-reporter {
        type inet:ipv4-address;
        description
          "The IPv4 address of the last host that has sent the
           report to join the multicast group.";
      }
      list source {
        key "source-address";
        description
          "List of multicast source information
           of the multicast group.";
        leaf source-address {
          type inet:ipv4-address;
          description
            "Multicast source address in group record.";
        }
        uses interface-state-source-attributes;
        leaf last-reporter {
          type inet:ipv4-address;
          description
            "The IPv4 address of the last host that has sent the
             report to join the multicast source and group.";
        }
        list host {
          if-feature "intf-explicit-tracking";
          key "host-address";
          description
            "List of hosts with the membership for the specific
             multicast source-group.";
          leaf host-address {
            type inet:ipv4-address;
            description
              "The IPv4 address of the host.";
          }
          uses interface-state-host-attributes;
        }
        // list host
      }
      // list source
    }
    // list group
  }
  // interface-state-attributes-igmp

  grouping interface-state-attributes-mld {
    description
      "Per-interface state attributes for MLD.";
    uses interface-state-attributes;
    leaf querier {
      type inet:ipv6-address;
      config false;
      mandatory true;
      description
        "The querier address in the subnet.";
    }
    leaf-list joined-group {
      if-feature "intf-join-group";
      type rt-types:ipv6-multicast-group-address;
      config false;
      description
        "The routers that joined this multicast group.";
    }
    list group {
      key "group-address";
      config false;
      description
        "Multicast group membership information
         that joined on the interface.";
      leaf group-address {
        type rt-types:ipv6-multicast-group-address;
        description
          "Multicast group address.";
      }
      uses interface-state-group-attributes;
      leaf last-reporter {
        type inet:ipv6-address;
        description
          "The IPv6 address of the last host that has sent the
           report to join the multicast group.";
      }
      list source {
        key "source-address";
        description
          "List of multicast sources of the multicast group.";
        leaf source-address {
          type inet:ipv6-address;
          description
            "Multicast source address in group record.";
        }
        uses interface-state-source-attributes;
        leaf last-reporter {
          type inet:ipv6-address;
          description
            "The IPv6 address of the last host that has sent the
             report to join the multicast source and group.";
        }
        list host {
          if-feature "intf-explicit-tracking";
          key "host-address";
          description
            "List of hosts with the membership for the specific
             multicast source-group.";
          leaf host-address {
            type inet:ipv6-address;
            description
              "The IPv6 address of the host.";
          }
          uses interface-state-host-attributes;
        }
        // list host
      }
      // list source
    }
    // list group
  }
  // interface-state-attributes-mld

  grouping interface-state-group-attributes {
    description
      "Per-interface state attributes for both IGMP and MLD
       groups.";
    leaf expire {
      type uint32;
      units "seconds";
      mandatory true;
      description
        "The time left before the multicast group state expires.";
    }
    leaf filter-mode {
      type enumeration {
        enum include {
          description
            "In include mode, reception of packets sent
             to the specified multicast address is requested
             only from those IP source addresses listed in the
             source-list parameter";
        }
        enum exclude {
          description
            "In exclude mode, reception of packets sent
             to the given multicast address is requested
             from all IP source addresses except those
             listed in the source-list parameter.";
        }
      }
      mandatory true;
      description
        "Filter mode for a multicast group,
         may be either include or exclude.";
    }
    leaf up-time {
      type uint32;
      units "seconds";
      mandatory true;
      description
        "The elapsed time since the device created multicast group
         record.";
    }
  }
  // interface-state-group-attributes

  grouping interface-state-source-attributes {
    description
      "Per-interface state attributes for both IGMP and MLD
       source-group records.";
    leaf expire {
      type uint32;
      units "seconds";
      mandatory true;
      description
        "The time left before multicast source-group state expires.";
    }
    leaf up-time {
      type uint32;
      units "seconds";
      mandatory true;
      description
        "The elapsed time since the device created multicast
         source-group record.";
    }
    leaf host-count {
      if-feature "intf-explicit-tracking";
      type uint32;
      description
        "The number of host addresses.";
    }
  }
  // interface-state-source-attributes

  grouping interface-state-host-attributes {
    description
      "Per-interface state attributes for both IGMP and MLD
       hosts of source-group records.";
    leaf host-filter-mode {
      type enumeration {
        enum include {
          description
            "In include mode.";
        }
        enum exclude {
          description
            "In exclude mode.";
        }
      }
      mandatory true;
      description
        "Filter mode for a multicast membership
         host may be either include or exclude.";
    }
  }
  // interface-state-host-attributes

  /*
   * Configuration and Operational state data nodes (NMDA version)
   */

  augment "/rt:routing/rt:control-plane-protocols/"
        + "rt:control-plane-protocol" {
    when "derived-from-or-self(rt:type, 'igmp-mld:igmp')" {
      description
        "This augmentation is only valid for a control-plane
         protocol instance of IGMP (type 'igmp').";
    }
    description
      "IGMP augmentation to routing control-plane protocol
       configuration and state.";
    container igmp {
      if-feature "feature-igmp";
      description
        "IGMP configuration and operational state data.";
      container global {
        description
          "Global attributes.";
        uses global-config-attributes;
        uses global-state-attributes;
      }
      container interfaces {
        description
          "Containing a list of interfaces.";
        uses interfaces-config-attributes-igmp {
          if-feature "interface-global-config";
          refine "query-interval" {
            default "125";
          }
          refine "query-max-response-time" {
            default "10";
          }
          refine "robustness-variable" {
            default "2";
          }
          refine "version" {
            default "2";
          }
        }
        list interface {
          key "interface-name";
          description
            "List of IGMP interfaces.";
          leaf interface-name {
            type if:interface-ref;
            must
              '/if:interfaces/if:interface[if:name = current()]/'
            + 'ip:ipv4' {
              error-message
                "The interface must have IPv4 configured, either "
              + "enabled or disabled.";
            }
            description
              "Reference to an entry in the global interface list.";
          }
          uses interface-config-attributes-igmp {
            if-feature "per-interface-config";
            refine "last-member-query-interval" {
              must '../version != 1 or '
                 + '(not(../version) and '
                 + '(../../version != 1 or not(../../version)))' {
                error-message "IGMPv1 does not support "
                            + "last-member-query-interval.";
              }
            }
            refine "max-group-sources" {
              must '../version = 3 or '
                 + '(not(../version) and (../../version = 3))' {
                error-message
                  "The version of IGMP must be 3 to support the "
                + "source-specific parameters.";
              }
            }
            refine "source-policy" {
              must '../version = 3 or '
                 + '(not(../version) and (../../version = 3))' {
                error-message
                  "The version of IGMP must be 3 to support the "
                + "source-specific parameters.";
              }
            }
            refine "explicit-tracking" {
              must '../version = 3 or '
                 + '(not(../version) and (../../version = 3))' {
                error-message
                  "The version of IGMP must be 3 to support the "
                + "explicit tracking function.";
              }
            }
            refine "lite-exclude-filter" {
              must '../version = 3 or '
                 + '(not(../version) and (../../version = 3))' {
                error-message
                  "The version of IGMP must be 3 to support the "
                + "simplified EXCLUDE filter in the Lightweight "
                + "IGMPv3 protocol.";
              }
            }
          }
          uses interface-state-attributes-igmp;
        }
        // interface
      }
      // interfaces

      /*
       * Actions
       */
      action clear-groups {
        if-feature "action-clear-groups";
        description
          "Clears the specified IGMP cache entries.";
        input {
          choice interface {
            mandatory true;
            description
              "Indicates the interface(s) from which the cache
               entries are cleared.";
            case name {
              leaf interface-name {
                type leafref {
                  path "/rt:routing/rt:control-plane-protocols/"
                     + "rt:control-plane-protocol/"
                     + "igmp-mld:igmp/igmp-mld:interfaces/"
                     + "igmp-mld:interface/igmp-mld:interface-name";
                }
                description
                  "Name of the IGMP interface.";
              }
            }
            case all {
              leaf all-interfaces {
                type empty;
                description
                  "IGMP groups from all interfaces are cleared.";
              }
            }
          }
          leaf group-address {
            type union {
              type enumeration {
                enum * {
                  description
                    "Any group address.";
                }
              }
              type rt-types:ipv4-multicast-group-address;
            }
            mandatory true;
            description
              "Multicast group IPv4 address.
               If the value '*' is specified, all IGMP group entries
               are cleared.";
          }
          leaf source-address {
            type rt-types:ipv4-multicast-source-address;
            mandatory true;
            description
              "Multicast source IPv4 address.
               If the value '*' is specified, all IGMP source-group
               entries are cleared.";
          }
        }
      }
      // action clear-groups
    }
    // igmp
  }
  // augment

  augment "/rt:routing/rt:control-plane-protocols/"
        + "rt:control-plane-protocol" {
    when "derived-from-or-self(rt:type, 'igmp-mld:mld')" {
      description
        "This augmentation is only valid for a control-plane
         protocol instance of IGMP (type 'mld').";
    }
    description
      "MLD augmentation to routing control-plane protocol
       configuration and state.";
    container mld {
      if-feature "feature-mld";
      description
        "MLD configuration and operational state data.";
      container global {
        description
          "Global attributes.";
        uses global-config-attributes;
        uses global-state-attributes;
      }
      container interfaces {
        description
          "Containing a list of interfaces.";
        uses interfaces-config-attributes-mld {
          if-feature "interface-global-config";
          refine "last-member-query-interval" {
            default "1";
          }
          refine "query-interval" {
            default "125";
          }
          refine "query-max-response-time" {
            default "10";
          }
          refine "require-router-alert" {
            default "true";
          }
          refine "robustness-variable" {
            default "2";
          }
          refine "version" {
            default "2";
          }
        }
        list interface {
          key "interface-name";
          description
            "List of MLD interfaces.";
          leaf interface-name {
            type if:interface-ref;
            must
              '/if:interfaces/if:interface[if:name = current()]/'
            + 'ip:ipv6' {
              error-message
                "The interface must have IPv6 configured, either "
              + "enabled or disabled.";
            }
            description
              "Reference to an entry in the global interface list.";
          }
          uses interface-config-attributes-mld {
            if-feature "per-interface-config";
            refine "max-group-sources" {
              must '../version = 2 or '
                 + '(not(../version) and '
                 + '(../../version = 2 or not(../../version)))' {
                error-message
                  "The version of MLD must be 2 to support the "
                + "source-specific parameters.";
              }
            }
            refine "source-policy" {
              must '../version = 2 or '
                 + '(not(../version) and '
                 + '(../../version = 2 or not(../../version)))' {
                error-message
                  "The version of MLD must be 2 to support the "
                + "source-specific parameters.";
              }
            }
            refine "explicit-tracking" {
              must '../version = 2 or '
                 + '(not(../version) and '
                 + '(../../version = 2 or not(../../version)))' {
                error-message
                  "The version of MLD must be 2 to support the "
                + "explicit tracking function.";
              }
            }
            refine "lite-exclude-filter" {
              must '../version = 2 or '
                 + '(not(../version) and '
                 + '(../../version = 2 or not(../../version)))' {
                error-message
                  "The version of MLD must be 2 to support the "
                + "simplified EXCLUDE filter in the Lightweight "
                + "MLDv2 protocol.";
              }
            }
          }
          uses interface-state-attributes-mld;
        }
        // interface
      }
      // interfaces

      /*
       * Actions
       */
      action clear-groups {
        if-feature "action-clear-groups";
        description
          "Clears the specified MLD cache entries.";
        input {
          choice interface {
            mandatory true;
            description
              "Indicates the interface(s) from which the cache
               entries are cleared.";
            case name {
              leaf interface-name {
                type leafref {
                  path "/rt:routing/rt:control-plane-protocols/"
                     + "rt:control-plane-protocol/"
                     + "igmp-mld:mld/igmp-mld:interfaces/"
                     + "igmp-mld:interface/igmp-mld:interface-name";
                }
                description
                  "Name of the MLD interface.";
              }
            }
            case all {
              leaf all-interfaces {
                type empty;
                description
                  "MLD groups from all interfaces are cleared.";
              }
            }
          }
          leaf group-address {
            type union {
              type enumeration {
                enum * {
                  description
                    "Any group address.";
                }
              }
              type rt-types:ipv6-multicast-group-address;
            }
            description
              "Multicast group IPv6 address.
               If the value '*' is specified, all MLD group entries
               are cleared.";
          }
          leaf source-address {
            type rt-types:ipv6-multicast-source-address;
            description
              "Multicast source IPv6 address.
               If the value '*' is specified, all MLD source-group
               entries are cleared.";
          }
        }
      }
      // action clear-mld-groups
    }
    // mld
  }
  // augment
}
----

[[s-5]]
[numbered=true,removeInRFC=false,toc=include]
== Security Considerations

The YANG module specified in this document defines a schema for data that is designed to be accessed via network management protocols such as NETCONF <<RFC6241,format=default>> or RESTCONF <<RFC8040,format=default>>. The lowest NETCONF layer is the secure transport layer, and the mandatory-to-implement secure transport is Secure Shell (SSH) <<RFC6242,format=default>>. The lowest RESTCONF layer is HTTPS, and the mandatory-to-implement secure transport is TLS <<RFC8446,format=default>>.

The Network Configuration Access Control Model (NACM) <<RFC8341,format=default>> provides the means to restrict access for particular NETCONF or RESTCONF users to a preconfigured subset of all available NETCONF or RESTCONF protocol operations and content.

There are a number of data nodes defined in this YANG module that are writable/creatable/deletable (i.e., config true, which is the default). These data nodes may be considered sensitive or vulnerable in some network environments. Write operations (e.g., edit-config) to these data nodes without proper protection can have a negative effect on network operations. These are the subtrees and data nodes and their sensitivity/vulnerability:
[align=left,alt=,]
....
Under /rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmp-mld:igmp,
....


[newline=true,spacing=normal]
igmp-mld:global:: This subtree specifies the configuration for the IGMP attributes at the global level on an IGMP instance. Modifying the configuration can cause IGMP membership to be deleted or reconstructed on all the interfaces of an IGMP instance.
igmp-mld:interfaces:: This subtree specifies the configuration for the IGMP attributes at the interface-global level on an IGMP instance. Modifying the configuration can cause IGMP membership to be deleted or reconstructed on all the interfaces of an IGMP instance.
igmp-mld:interfaces/interface:: This subtree specifies the configuration for the IGMP attributes at the interface level on an IGMP instance. Modifying the configuration can cause IGMP membership to be deleted or reconstructed on a specific interface of an IGMP instance.
[align=left,alt=,]
....
Under /rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmp-mld:mld,
....


[newline=true,spacing=normal]
igmp-mld:global:: This subtree specifies the configuration for the MLD attributes at the global level on an MLD instance. Modifying the configuration can cause MLD membership to be deleted or reconstructed on all the interfaces of an MLD instance.
igmp-mld:interfaces:: This subtree specifies the configuration for the MLD attributes at the interface-global level on an MLD instance. Modifying the configuration can cause MLD membership to be deleted or reconstructed on all the interfaces of an MLD instance.
igmp-mld:interfaces/interface:: This subtree specifies the configuration for the MLD attributes at the interface level on a device. Modifying the configuration can cause MLD membership to be deleted or reconstructed on a specific interface of an MLD instance.

Unauthorized access to any data node of these subtrees can adversely affect the membership records of multicast routing subsystem on the local device. This may lead to network malfunctions, delivery of packets to inappropriate destinations, and other problems.

Some of the readable data nodes in this YANG module may be considered sensitive or vulnerable in some network environments. It is thus important to control read access (e.g., via get, get-config, or notification) to these data nodes. These are the subtrees and data nodes and their sensitivity/vulnerability:
[align=left,alt=,]
....
/rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmmp-mld:igmp

/rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmp-mld:mld
....


Unauthorized access to any data node of the above subtree can disclose the operational state information of IGMP or MLD on this device.

Some of the action operations in this YANG module may be considered sensitive or vulnerable in some network environments. It is thus important to control access to these operations. These are the operations and their sensitivity/vulnerability:
[align=left,alt=,]
....
/rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmmp-mld:igmp/igmmp-mld:clear-groups

/rt:routing/rt:control-plane-protocols
/rt:control-plane-protocol/igmp-mld:mld/igmp-mld:clear-groups
....

Unauthorized access to any of the above action operations can delete the IGMP or MLD membership records on this device.

[[s-6]]
[numbered=true,removeInRFC=false,toc=include]
== IANA Considerations

This document registers the following namespace URIs in the IETF XML registry <<RFC3688,format=default>>:

[newline=false,spacing=normal]
URI::: urn:ietf:params:xml:ns:yang:ietf-igmp-mld
Registrant Contact::: The IESG.
XML::: N/A; the requested URI is an XML namespace.

This document registers the following YANG modules in the YANG Module Names registry <<RFC6020,format=default>>:

[newline=false,spacing=normal]
Name::: ietf-igmp-mld
Namespace::: urn:ietf:params:xml:ns:yang:ietf-igmp-mld
Prefix::: igmp-mld
Reference::: RFC 8652

[bibliography]
== Normative References
++++
<reference anchor="RFC1112" derivedAnchor="RFC1112" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc1112"><front><title>Host extensions for IP multicasting</title>
<author fullname="S.E. Deering" initials="S.E." surname="Deering"><organization showOnFrontPage="true"></organization>
</author>
<date month="August" year="1989"></date>
<abstract><t>This memo specifies the extensions required of a host implementation of the Internet Protocol (IP) to support multicasting.  Recommended procedure for IP multicasting in the Internet.  This RFC obsoletes RFCs 998 and 1054.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="STD" value="5"></seriesInfo>
<seriesInfo name="RFC" value="1112"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC1112"></seriesInfo>
</reference>
<reference anchor="RFC2119" derivedAnchor="RFC2119" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc2119"><front><title>Key words for use in RFCs to Indicate Requirement Levels</title>
<author fullname="S. Bradner" initials="S." surname="Bradner"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="1997"></date>
<abstract><t>In many standards track documents several words are used to signify the requirements in the specification.  These words are often capitalized. This document defines these words as they should be interpreted in IETF documents.  This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.</t>
</abstract>
</front>
<seriesInfo name="BCP" value="14"></seriesInfo>
<seriesInfo name="RFC" value="2119"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC2119"></seriesInfo>
</reference>
<reference anchor="RFC2236" derivedAnchor="RFC2236" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc2236"><front><title>Internet Group Management Protocol, Version 2</title>
<author fullname="W. Fenner" initials="W." surname="Fenner"><organization showOnFrontPage="true"></organization>
</author>
<date month="November" year="1997"></date>
<abstract><t>This memo documents IGMPv2, used by IP hosts to report their multicast group memberships to routers.  It updates STD 5, RFC 1112.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2236"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC2236"></seriesInfo>
</reference>
<reference anchor="RFC2710" derivedAnchor="RFC2710" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc2710"><front><title>Multicast Listener Discovery (MLD) for IPv6</title>
<author fullname="S. Deering" initials="S." surname="Deering"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="W. Fenner" initials="W." surname="Fenner"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="B. Haberman" initials="B." surname="Haberman"><organization showOnFrontPage="true"></organization>
</author>
<date month="October" year="1999"></date>
<abstract><t>This document specifies the protocol used by an IPv6 router to discover the presence of multicast listeners (that is, nodes wishing to receive multicast packets) on its directly attached links, and to discover specifically which multicast addresses are of interest to those neighboring nodes.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="2710"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC2710"></seriesInfo>
</reference>
<reference anchor="RFC3376" derivedAnchor="RFC3376" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc3376"><front><title>Internet Group Management Protocol, Version 3</title>
<author fullname="B. Cain" initials="B." surname="Cain"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="S. Deering" initials="S." surname="Deering"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="I. Kouvelas" initials="I." surname="Kouvelas"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="B. Fenner" initials="B." surname="Fenner"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Thyagarajan" initials="A." surname="Thyagarajan"><organization showOnFrontPage="true"></organization>
</author>
<date month="October" year="2002"></date>
</front>
<seriesInfo name="RFC" value="3376"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC3376"></seriesInfo>
</reference>
<reference anchor="RFC3688" derivedAnchor="RFC3688" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc3688"><front><title>The IETF XML Registry</title>
<author fullname="M. Mealling" initials="M." surname="Mealling"><organization showOnFrontPage="true"></organization>
</author>
<date month="January" year="2004"></date>
<abstract><t>This document describes an IANA maintained registry for IETF standards which use Extensible Markup Language (XML) related items such as Namespaces, Document Type Declarations (DTDs), Schemas, and Resource Description Framework (RDF) Schemas.</t>
</abstract>
</front>
<seriesInfo name="BCP" value="81"></seriesInfo>
<seriesInfo name="RFC" value="3688"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC3688"></seriesInfo>
</reference>
<reference anchor="RFC3810" derivedAnchor="RFC3810" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc3810"><front><title>Multicast Listener Discovery Version 2 (MLDv2) for IPv6</title>
<author fullname="R. Vida" initials="R." role="editor" surname="Vida"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="L. Costa" initials="L." role="editor" surname="Costa"><organization showOnFrontPage="true"></organization>
</author>
<date month="June" year="2004"></date>
<abstract><t>This document updates RFC 2710, and it specifies Version 2 of the ulticast Listener Discovery Protocol (MLDv2).  MLD is used by an IPv6 router to discover the presence of multicast listeners on directly attached links, and to discover which multicast addresses are of interest to those neighboring nodes.  MLDv2 is designed to be interoperable with MLDv1.  MLDv2 adds the ability for a node to report interest in listening to packets with a particular multicast address only from specific source addresses or from all sources except for specific source addresses.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="3810"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC3810"></seriesInfo>
</reference>
<reference anchor="RFC4607" derivedAnchor="RFC4607" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc4607"><front><title>Source-Specific Multicast for IP</title>
<author fullname="H. Holbrook" initials="H." surname="Holbrook"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="B. Cain" initials="B." surname="Cain"><organization showOnFrontPage="true"></organization>
</author>
<date month="August" year="2006"></date>
<abstract><t>IP version 4 (IPv4) addresses in the 232/8 (232.0.0.0 to 232.255.255.255) range are designated as source-specific multicast (SSM) destination addresses and are reserved for use by source-specific applications and protocols.  For IP version 6 (IPv6), the address prefix FF3x::/32 is reserved for source-specific multicast use.  This document defines an extension to the Internet network service that applies to datagrams sent to SSM addresses and defines the host and router requirements to support this extension.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="4607"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC4607"></seriesInfo>
</reference>
<reference anchor="RFC6020" derivedAnchor="RFC6020" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc6020"><front><title>YANG - A Data Modeling Language for the Network Configuration Protocol (NETCONF)</title>
<author fullname="M. Bjorklund" initials="M." role="editor" surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<date month="October" year="2010"></date>
<abstract><t>YANG is a data modeling language used to model configuration and state data manipulated by the Network Configuration Protocol (NETCONF), NETCONF remote procedure calls, and NETCONF notifications. [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="6020"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC6020"></seriesInfo>
</reference>
<reference anchor="RFC6241" derivedAnchor="RFC6241" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc6241"><front><title>Network Configuration Protocol (NETCONF)</title>
<author fullname="R. Enns" initials="R." role="editor" surname="Enns"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="M. Bjorklund" initials="M." role="editor" surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="J. Schoenwaelder" initials="J." role="editor" surname="Schoenwaelder"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Bierman" initials="A." role="editor" surname="Bierman"><organization showOnFrontPage="true"></organization>
</author>
<date month="June" year="2011"></date>
<abstract><t>The Network Configuration Protocol (NETCONF) defined in this document provides mechanisms to install, manipulate, and delete the configuration of network devices.  It uses an Extensible Markup Language (XML)-based data encoding for the configuration data as well as the protocol messages.  The NETCONF protocol operations are realized as remote procedure calls (RPCs).  This document obsoletes RFC 4741.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="6241"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC6241"></seriesInfo>
</reference>
<reference anchor="RFC6242" derivedAnchor="RFC6242" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc6242"><front><title>Using the NETCONF Protocol over Secure Shell (SSH)</title>
<author fullname="M. Wasserman" initials="M." surname="Wasserman"><organization showOnFrontPage="true"></organization>
</author>
<date month="June" year="2011"></date>
<abstract><t>This document describes a method for invoking and running the Network Configuration Protocol (NETCONF) within a Secure Shell (SSH) session as an SSH subsystem.  This document obsoletes RFC 4742.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="6242"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC6242"></seriesInfo>
</reference>
<reference anchor="RFC6991" derivedAnchor="RFC6991" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc6991"><front><title>Common YANG Data Types</title>
<author fullname="J. Schoenwaelder" initials="J." role="editor" surname="Schoenwaelder"><organization showOnFrontPage="true"></organization>
</author>
<date month="July" year="2013"></date>
<abstract><t>This document introduces a collection of common data types to be used with the YANG data modeling language.  This document obsoletes RFC 6021.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="6991"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC6991"></seriesInfo>
</reference>
<reference anchor="RFC7950" derivedAnchor="RFC7950" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc7950"><front><title>The YANG 1.1 Data Modeling Language</title>
<author fullname="M. Bjorklund" initials="M." role="editor" surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<date month="August" year="2016"></date>
<abstract><t>YANG is a data modeling language used to model configuration data, state data, Remote Procedure Calls, and notifications for network management protocols.  This document describes the syntax and semantics of version 1.1 of the YANG language.  YANG version 1.1 is a maintenance release of the YANG language, addressing ambiguities and defects in the original specification.  There are a small number of backward incompatibilities from YANG version 1.  This document also specifies the YANG mappings to the Network Configuration Protocol (NETCONF).</t>
</abstract>
</front>
<seriesInfo name="RFC" value="7950"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC7950"></seriesInfo>
</reference>
<reference anchor="RFC8040" derivedAnchor="RFC8040" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8040"><front><title>RESTCONF Protocol</title>
<author fullname="A. Bierman" initials="A." surname="Bierman"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="K. Watsen" initials="K." surname="Watsen"><organization showOnFrontPage="true"></organization>
</author>
<date month="January" year="2017"></date>
<abstract><t>This document describes an HTTP-based protocol that provides a programmatic interface for accessing data defined in YANG, using the datastore concepts defined in the Network Configuration Protocol (NETCONF).</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8040"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8040"></seriesInfo>
</reference>
<reference anchor="RFC8174" derivedAnchor="RFC8174" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8174"><front><title>Ambiguity of Uppercase vs Lowercase in RFC 2119 Key Words</title>
<author fullname="B. Leiba" initials="B." surname="Leiba"><organization showOnFrontPage="true"></organization>
</author>
<date month="May" year="2017"></date>
<abstract><t>RFC 2119 specifies common key words that may be used in protocol  specifications.  This document aims to reduce the ambiguity by clarifying that only UPPERCASE usage of the key words have the  defined special meanings.</t>
</abstract>
</front>
<seriesInfo name="BCP" value="14"></seriesInfo>
<seriesInfo name="RFC" value="8174"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8174"></seriesInfo>
</reference>
<reference anchor="RFC8294" derivedAnchor="RFC8294" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8294"><front><title>Common YANG Data Types for the Routing Area</title>
<author fullname="X. Liu" initials="X." surname="Liu"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="Y. Qu" initials="Y." surname="Qu"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Lindem" initials="A." surname="Lindem"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="C. Hopps" initials="C." surname="Hopps"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="L. Berger" initials="L." surname="Berger"><organization showOnFrontPage="true"></organization>
</author>
<date month="December" year="2017"></date>
<abstract><t>This document defines a collection of common data types using the YANG data modeling language.  These derived common types are designed to be imported by other modules defined in the routing area.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8294"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8294"></seriesInfo>
</reference>
<reference anchor="RFC8341" derivedAnchor="RFC8341" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8341"><front><title>Network Configuration Access Control Model</title>
<author fullname="A. Bierman" initials="A." surname="Bierman"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>The standardization of network configuration interfaces for use with the Network Configuration Protocol (NETCONF) or the RESTCONF protocol requires a structured and secure operating environment that promotes human usability and multi-vendor interoperability.  There is a need for standard mechanisms to restrict NETCONF or RESTCONF protocol access for particular users to a preconfigured subset of all available NETCONF or RESTCONF protocol operations and content.  This document defines such an access control model.</t>
<t>This document obsoletes RFC 6536.</t>
</abstract>
</front>
<seriesInfo name="STD" value="91"></seriesInfo>
<seriesInfo name="RFC" value="8341"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8341"></seriesInfo>
</reference>
<reference anchor="RFC8342" derivedAnchor="RFC8342" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8342"><front><title>Network Management Datastore Architecture (NMDA)</title>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="J. Schoenwaelder" initials="J." surname="Schoenwaelder"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="P. Shafer" initials="P." surname="Shafer"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="K. Watsen" initials="K." surname="Watsen"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="R. Wilton" initials="R." surname="Wilton"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>Datastores are a fundamental concept binding the data models written in the YANG data modeling language to network management protocols such as the Network Configuration Protocol (NETCONF) and RESTCONF. This document defines an architectural framework for datastores based on the experience gained with the initial simpler model, addressing requirements that were not well supported in the initial model.  This document updates RFC 7950.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8342"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8342"></seriesInfo>
</reference>
<reference anchor="RFC8343" derivedAnchor="RFC8343" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8343"><front><title>A YANG Data Model for Interface Management</title>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>This document defines a YANG data model for the management of network interfaces.  It is expected that interface-type-specific data models augment the generic interfaces data model defined in this document. The data model includes definitions for configuration and system state (status information and counters for the collection of statistics).</t>
<t>The YANG data model in this document conforms to the Network Management Datastore Architecture (NMDA) defined in RFC 8342.</t>
<t>This document obsoletes RFC 7223.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8343"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8343"></seriesInfo>
</reference>
<reference anchor="RFC8344" derivedAnchor="RFC8344" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8344"><front><title>A YANG Data Model for IP Management</title>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>This document defines a YANG data model for management of IP implementations.  The data model includes configuration and system state.</t>
<t>The YANG data model in this document conforms to the Network Management Datastore Architecture defined in RFC 8342.</t>
<t>This document obsoletes RFC 7277.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8344"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8344"></seriesInfo>
</reference>
<reference anchor="RFC8349" derivedAnchor="RFC8349" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8349"><front><title>A YANG Data Model for Routing Management (NMDA Version)</title>
<author fullname="L. Lhotka" initials="L." surname="Lhotka"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Lindem" initials="A." surname="Lindem"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="Y. Qu" initials="Y." surname="Qu"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>This document specifies three YANG modules and one submodule. Together, they form the core routing data model that serves as a framework for configuring and managing a routing subsystem.  It is expected that these modules will be augmented by additional YANG modules defining data models for control-plane protocols, route filters, and other functions.  The core routing data model provides common building blocks for such extensions -- routes, Routing Information Bases (RIBs), and control-plane protocols.</t>
<t>The YANG modules in this document conform to the Network Management Datastore Architecture (NMDA).  This document obsoletes RFC 8022.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8349"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8349"></seriesInfo>
</reference>
<reference anchor="RFC8446" derivedAnchor="RFC8446" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8446"><front><title>The Transport Layer Security (TLS) Protocol Version 1.3</title>
<author fullname="E. Rescorla" initials="E." surname="Rescorla"><organization showOnFrontPage="true"></organization>
</author>
<date month="August" year="2018"></date>
<abstract><t>This document specifies version 1.3 of the Transport Layer Security (TLS) protocol.  TLS allows client/server applications to communicate over the Internet in a way that is designed to prevent eavesdropping, tampering, and message forgery.</t>
<t>This document updates RFCs 5705 and 6066, and obsoletes RFCs 5077, 5246, and 6961.  This document also specifies new requirements for TLS 1.2 implementations.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8446"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8446"></seriesInfo>
</reference>
<reference anchor="RFC8519" derivedAnchor="RFC8519" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8519"><front><title>YANG Data Model for Network Access Control Lists (ACLs)</title>
<author fullname="M. Jethanandani" initials="M." surname="Jethanandani"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="S. Agarwal" initials="S." surname="Agarwal"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="L. Huang" initials="L." surname="Huang"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="D. Blair" initials="D." surname="Blair"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2019"></date>
<abstract><t>This document defines a data model for Access Control Lists (ACLs). An ACL is a user-ordered set of rules used to configure the forwarding behavior in a device.  Each rule is used to find a match on a packet and define actions that will be performed on the packet.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8519"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8519"></seriesInfo>
</reference>
++++

[bibliography]
== Informative References
++++
<reference anchor="RFC3569" derivedAnchor="RFC3569" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc3569"><front><title>An Overview of Source-Specific Multicast (SSM)</title>
<author fullname="S. Bhattacharyya" initials="S." role="editor" surname="Bhattacharyya"><organization showOnFrontPage="true"></organization>
</author>
<date month="July" year="2003"></date>
<abstract><t>The purpose of this document is to provide an overview of Source-Specific Multicast (SSM) and issues related to its deployment. It discusses how the SSM service model addresses the challenges faced in inter-domain multicast deployment, changes needed to routing protocols and applications to deploy SSM and interoperability issues with current multicast service models.  This memo provides information for the Internet community.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="3569"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC3569"></seriesInfo>
</reference>
<reference anchor="RFC4541" derivedAnchor="RFC4541" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc4541"><front><title>Considerations for Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) Snooping Switches</title>
<author fullname="M. Christensen" initials="M." surname="Christensen"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="K. Kimball" initials="K." surname="Kimball"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="F. Solensky" initials="F." surname="Solensky"><organization showOnFrontPage="true"></organization>
</author>
<date month="May" year="2006"></date>
<abstract><t>This memo describes the recommendations for Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) snooping switches.  These are based on best current practices for IGMPv2, with further considerations for IGMPv3- and MLDv2-snooping.  Additional areas of relevance, such as link layer topology changes and Ethernet-specific encapsulation issues, are also considered.  This memo provides information for the Internet community.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="4541"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC4541"></seriesInfo>
</reference>
<reference anchor="RFC4605" derivedAnchor="RFC4605" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc4605"><front><title>Internet Group Management Protocol (IGMP) / Multicast Listener Discovery (MLD)-Based Multicast Forwarding ("IGMP/MLD Proxying")</title>
<author fullname="B. Fenner" initials="B." surname="Fenner"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="H. He" initials="H." surname="He"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="B. Haberman" initials="B." surname="Haberman"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="H. Sandick" initials="H." surname="Sandick"><organization showOnFrontPage="true"></organization>
</author>
<date month="August" year="2006"></date>
<abstract><t>In certain topologies, it is not necessary to run a multicast routing protocol.  It is sufficient for a device to learn and proxy group membership information and simply forward multicast packets based upon that information.  This document describes a mechanism for forwarding based solely upon Internet Group Management Protocol (IGMP) or Multicast Listener Discovery (MLD) membership information.  [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="4605"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC4605"></seriesInfo>
</reference>
<reference anchor="RFC5790" derivedAnchor="RFC5790" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc5790"><front><title>Lightweight Internet Group Management Protocol Version 3 (IGMPv3) and Multicast Listener Discovery Version 2 (MLDv2) Protocols</title>
<author fullname="H. Liu" initials="H." surname="Liu"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="W. Cao" initials="W." surname="Cao"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="H. Asaeda" initials="H." surname="Asaeda"><organization showOnFrontPage="true"></organization>
</author>
<date month="February" year="2010"></date>
<abstract><t>This document describes lightweight IGMPv3 and MLDv2 protocols (LW- IGMPv3 and LW-MLDv2), which simplify the standard (full) versions of IGMPv3 and MLDv2.  The interoperability with the full versions and the previous versions of IGMP and MLD is also taken into account.   [STANDARDS-TRACK]</t>
</abstract>
</front>
<seriesInfo name="RFC" value="5790"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC5790"></seriesInfo>
</reference>
<reference anchor="RFC6636" derivedAnchor="RFC6636" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc6636"><front><title>Tuning the Behavior of the Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) for Routers in Mobile and Wireless Networks</title>
<author fullname="H. Asaeda" initials="H." surname="Asaeda"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="H. Liu" initials="H." surname="Liu"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="Q. Wu" initials="Q." surname="Wu"><organization showOnFrontPage="true"></organization>
</author>
<date month="May" year="2012"></date>
<abstract><t>The Internet Group Management Protocol (IGMP) and Multicast Listener Discovery (MLD) are the protocols used by hosts and multicast routers to exchange their IP multicast group memberships with each other. This document describes ways to achieve IGMPv3 and MLDv2 protocol optimization for mobility and aims to become a guideline for the tuning of IGMPv3/MLDv2 Queries, timers, and counter values.  This  document is not an Internet Standards Track specification; it is published for informational purposes.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="6636"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC6636"></seriesInfo>
</reference>
<reference anchor="RFC8340" derivedAnchor="RFC8340" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8340"><front><title>YANG Tree Diagrams</title>
<author fullname="M. Bjorklund" initials="M." surname="Bjorklund"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="L. Berger" initials="L." role="editor" surname="Berger"><organization showOnFrontPage="true"></organization>
</author>
<date month="March" year="2018"></date>
<abstract><t>This document captures the current syntax used in YANG module tree diagrams.  The purpose of this document is to provide a single location for this definition.  This syntax may be updated from time to time based on the evolution of the YANG language.</t>
</abstract>
</front>
<seriesInfo name="BCP" value="215"></seriesInfo>
<seriesInfo name="RFC" value="8340"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8340"></seriesInfo>
</reference>
<reference anchor="RFC8407" derivedAnchor="RFC8407" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8407"><front><title>Guidelines for Authors and Reviewers of Documents Containing YANG Data Models</title>
<author fullname="A. Bierman" initials="A." surname="Bierman"><organization showOnFrontPage="true"></organization>
</author>
<date month="October" year="2018"></date>
<abstract><t>This memo provides guidelines for authors and reviewers of specifications containing YANG modules.  Recommendations and procedures are defined, which are intended to increase interoperability and usability of Network Configuration Protocol (NETCONF) and RESTCONF protocol implementations that utilize YANG modules.  This document obsoletes RFC 6087.</t>
</abstract>
</front>
<seriesInfo name="BCP" value="216"></seriesInfo>
<seriesInfo name="RFC" value="8407"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8407"></seriesInfo>
</reference>
<reference anchor="RFC8639" derivedAnchor="RFC8639" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8639"><front><title>Subscription to YANG Notifications</title>
<author fullname="E. Voit" initials="E." surname="Voit"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Clemm" initials="A." surname="Clemm"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Gonzalez Prieto" initials="A." surname="Gonzalez Prieto"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="E. Nilsen-Nygaard" initials="E." surname="Nilsen-Nygaard"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="A. Tripathy" initials="A." surname="Tripathy"><organization showOnFrontPage="true"></organization>
</author>
<date month="September" year="2019"></date>
<abstract><t>This document defines a YANG data model and associated mechanisms enabling subscriber-specific subscriptions to a publisher's event streams.  Applying these elements allows a subscriber to request and receive a continuous, customized feed of publisher-generated information.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8639"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8639"></seriesInfo>
</reference>
<reference anchor="RFC8641" derivedAnchor="RFC8641" quoteTitle="true" target="https://www.rfc-editor.org/info/rfc8641"><front><title>Subscription to YANG Notifications for Datastore Updates</title>
<author fullname="A. Clemm" initials="A." surname="Clemm"><organization showOnFrontPage="true"></organization>
</author>
<author fullname="E. Voit" initials="E." surname="Voit"><organization showOnFrontPage="true"></organization>
</author>
<date month="September" year="2019"></date>
<abstract><t>This document describes a mechanism that allows subscriber applications to request a continuous and customized stream of updates from a YANG datastore.  Providing such visibility into updates enables new capabilities based on the remote mirroring and monitoring of configuration and operational state.</t>
</abstract>
</front>
<seriesInfo name="RFC" value="8641"></seriesInfo>
<seriesInfo name="DOI" value="10.17487/RFC8641"></seriesInfo>
</reference>
++++

[appendix,numbered=false,removeInRFC=false,toc=include]
== Acknowledgments

The authors would like to thank Steve Baillargeon, Hu Fangwei, Robert Kebler, Tanmoy Kundu, and Stig Venaas for their valuable contributions.

[appendix,numbered=false,removeInRFC=false,toc=include]
== Contributors
[align=left,alt=,]
....
Yisong Liu
Huawei Technologies
China

Email: liuyisong@huawei.com
....
