= Metanorma mnconvert

image:https://github.com/metanorma/mnconvert/workflows/ubuntu/badge.svg["Build Status", link="https://github.com/metanorma/mnconvert/actions?workflow=ubuntu"]
image:https://github.com/metanorma/mnconvert/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/mnconvert/actions?workflow=macos"]
image:https://github.com/metanorma/mnconvert/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/mnconvert/actions?workflow=windows"]

== Installing Build Tools

You will need the `maven` build tool and `make`.

* https://www.baeldung.com/install-maven-on-windows-linux-mac[How to install Maven on Windows, Linux, Mac]


== Usage


1. Check ISO/NISO STS xml against XSD, DTD.
[source,sh]
----
java -jar mnconvert.jar xml_file [options]
----

options:
- `--check-type`, `-ct` - Check against XSD NISO (value xsd-niso, default), DTD ISO (dtd-iso), DTD NISO (dtd-niso) (Default: xsd-niso)


2. Convert ISO/NISO STS xml to Metanorma xml or adoc.
[source,sh]
----
java -jar mnconvert.jar xml_file [options]
----

- `--xsl-file`, `-s` - path to XSL file, optional
- `--output`, `-o` - path to output file, optional
- `--output-format`, `-of` - xml|adoc(default), optional
- `--imagesdir`, `-img` - folder with images (default 'images'), optional
- `--split-bibdata`, `-sb` - create Metanorma Adoc and Relaton XML, optional
- `--type`, `-t` - type of standard to generate (iso, bsi, etc.), optional

3. Convert Metanorma xml to ISO/NISO STS xml.
[source,sh]
----
java -jar mnconvert.jar xml_file [options]
----

- `--xsl-file`, `-s` - path to XSL file, optional
- `--output`, `-o` - path to output file, optional
- `--output-format`, -of - iso|niso(default), optional
- `--check-type`, `-ct` - check against XSD NISO (value 'xsd-niso', default), DTD ISO (value 'dtd-iso'), DTD NISO (value 'dtd-niso')
                            
Common options:
- `--version`, `-v` - display application version, optional
- `--debug`, `-d` turn-on debug mode (print additional debug information into output file), optional

e.g.

[source,sh]
----
java -jar target/mnconvert-1.0.jar tests/iso-tc154-8601-1-en.xml --output tests/iso-tc154-8601-1-en.out.xml
----

NOTE: Input XML format (Metanorma or STS ISO/NISO) determines programmatically by root element of input file:
- Metanorma XML - *-standard or metanorma-collection
- ISO/STS in another cases
but you can specify it obviously by parameter --input-format, -if (values: metanorma|sts)

NOTE: Output format (Metanorma or STS) determines programmatically by root element of input file:
- STS NISO XML for input Metanorma XML
- Metanorma for input STS ISO/NISO XML




== Building the package

[source,sh]
----
make all
----


== Releasing a new version

Update version in `pom.xml`, e.g.:

[source,xml]
----
<groupId>com.metanorma</groupId>
<artifactId>mnconvert</artifactId>
<version>1.0</version>
<name>Metanorma XML to NISO STS XML two-directional converter</name>
----

Build the package using instructions above, the package will be created at:
`target/mnconvert-{version}.jar`

Tag the same version in Git:

[source,xml]
----
git tag v1.0
git push origin v1.0
----

Then the corresponding GitHub release will be automatically created at:
https://github.com/metanorma/mnconvert/releases

And downloadable at:
`https://github.com/metanorma/mnconvert/releases/download/v{version}/mnconvert-{version}.jar`


== Testing

The testing environment utilizes these tools:

* `make`


Running the tests:

[source,sh]
----
make test
----


== Copyright

Ribose Inc.
