package org.metanorma.validator;


public enum CheckAgainstEnum {
   XSD_NISO_INTERCHANGE_MATHML2, XSD_NISO_INTERCHANGE_MATHML3, XSD_NISO_EXTENDED_MATHML2, XSD_NISO_EXTENDED_MATHML3, 
   DTD_ISO, 
   DTD_NISO_INTERCHANGE_MATHML2, DTD_NISO_INTERCHANGE_MATHML3, DTD_NISO_EXTENDED_MATHML2, DTD_NISO_EXTENDED_MATHML3    
}
