
[[sec_3]]
== Terms and definitions

For the purposes of this document, the following terms and definitions apply.

ISO and IEC maintain terminological databases for use in standardization at the following addresses:



* ISO Online browsing platform: available at http://www.iso.org/obp

* IEC Electropedia: available at http://www.electropedia.org


=== paddy

[%metadata]
grammar::
isNoun::: true

alt:[paddy rice]

[%metadata]
grammar::
isNoun::: true

alt:[rough rice]

[%metadata]
grammar::
isNoun::: true


rice retaining its husk after threshing

[.source]
<<ref_7,clause 3.1>>

=== husked rice

[%metadata]
grammar::
isNoun::: true

alt:[cargo rice]

[%metadata]
grammar::
isNoun::: true


(**term “paddy” not resolved**) from which the husk only has been removed

[.source]
<<ref_7,clause 3.2>>,The term “cargo rice” is shown as deprecated, and Note 1 to entry is not included here

=== milled rice

[%metadata]
grammar::
isNoun::: true

alt:[white rice]

[%metadata]
grammar::
isNoun::: true


(**term “husked rice” not resolved**) from which almost all of the bran and embryo have been removed by milling

[.source]
<<ref_7,clause 3.3>>

=== parboiled rice

[%metadata]
grammar::
isNoun::: true


rice whose starch has been fully gelatinized by soaking  (**term “paddy” not resolved**) rice or  (**term “husked rice” not resolved**) in water followed by a heat treatment and a drying process

=== waxy rice

[%metadata]
grammar::
isNoun::: true


variety of rice whose kernels have a white and opaque appearance

NOTE: The starch of waxy rice consists almost entirely of amylopectin. The kernels have a tendency to stick together after cooking. 


=== extraneous matter

[%metadata]
grammar::
isNoun::: true

alt:[EM]

[%metadata]
grammar::
isNoun::: true

alt:[rice]

[%metadata]
grammar::
isNoun::: true


organic and inorganic components other than whole or broken kernels

====
Foreign seeds, husks, bran, sand, dust. 
====

=== HDK

[%metadata]
grammar::
isNoun::: true

alt:[heat-damaged kernel]

[%metadata]
grammar::
isNoun::: true


kernel, whole or broken, which has changed its normal colour as a result of heating

NOTE: This category includes whole or broken kernels that are yellow due to alteration. Parboiled rice in a batch of non-parboiled rice is also included in this category. 


=== damaged kernel

[%metadata]
grammar::
isNoun::: true


kernel, whole or broken, showing obvious deterioration due to moisture, pests, disease or other causes, but excluding  (**term “HDK” not resolved**)

=== immature kernel

[%metadata]
grammar::
isNoun::: true

alt:[unripe kernel]

[%metadata]
grammar::
isNoun::: true


kernel, whole or broken, which is unripe and/or underdeveloped

=== husked rice yield

[%metadata]
grammar::
isNoun::: true


amount of husked rice obtained from paddy

[.source]
<<ISO_6646,clause 3.1>>

=== nitrogen content

[%metadata]
grammar::
isNoun::: true


quantity of nitrogen determined after application of the procedure described

NOTE: It is expressed as a mass fraction of dry product, as a percentage. 


[.source]
<<norm_ref_6,clause 3.1>>

=== crude protein content

[%metadata]
grammar::
isNoun::: true


quantity of crude protein obtained from the nitrogen content as determined by applying the specified method, calculated by multiplying this content by an appropriate factor depending on the type of cereal or pulse

NOTE: It is expressed as a mass fraction of dry product, as a percentage. 


[.source]
<<norm_ref_6,clause 3.2>>

=== gelatinization

[%metadata]
grammar::
isNoun::: true


hydration process conferring the jelly-like state typical of the coagulated colloids, which are named “gels”, on kernels

NOTE: See <<fig_C.1>>. 


[.source]
<<ref_8,clause 3.1>>

=== gel state

[%metadata]
grammar::
isNoun::: true


condition reached as a consequence of  (**term “gelatinization” not resolved**), when the kernel is fully transparent and absolutely free from whitish and opaque granules after being pressed between two glass sheets

[.source]
<<ref_8,clause 3.2>>

=== gelatinization time

[%metadata]
grammar::
isNoun::: true

alt:[

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<msub>
<mi>t</mi>
<mn>90</mn>
</msub>
</math>
++++

]

[%metadata]
grammar::
isNoun::: true


time necessary for 90 % of the kernels to pass from their natural state to the  (**term “gel state” not resolved**)

[.source]
<<ref_8,clause 3.3>>

