
[[sec_D]]
[appendix,obligation=informative]
== Results of interlaboratory test for husked rice yields

An interlaboratory test <<ref_14,<<ref_14>>>> was carried out by the ENR [Rice Research Centre (Italy)] in accordance with <<ref_2,ISO 5725-1>> and <<ref_3,ISO 5725-2>>, with the participation of 15 laboratories. Each laboratory carried out three determinations on four different types of kernel. The statistical results are shown in <<tab_D.1>>.

[[tab_D.1]]
.Repeatability and reproducibility of husked rice yield
[cols="1,1,1,1,1",options="header",headerrows=2,width=100%]
|===
.2+^|Description 4+^|Rice sample
|Arborio ^|Drago footnote:[Parboiled rice.] ^|Balilla ^|Thaibonnet

|Number of laboratories retained after eliminating outliers ^|13 ^|11 ^|13 ^|13
|Mean value, g/100 g ^|81,2 ^|82,0 ^|81,8 ^|77,7
|Standard deviation of repeatability, 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<msub>
<mi>s</mi>
<mi>r</mi>
</msub>
</math>
++++

, g/100 g ^|0,41 ^|0,15 ^|0,31 ^|0,53
|Coefficient of variation of repeatability, % ^|0,5 ^|0,2 ^|0,4 ^|0,7
|Repeatability limit, 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mi>r</mi>
</math>
++++

 (= 2,83 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<msub>
<mi>s</mi>
<mi>r</mi>
</msub>
</math>
++++

) ^|1,16 ^|0,42 ^|0,88 ^|1,50
|Standard deviation of reproducibility, 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<msub>
<mi>s</mi>
<mi>R</mi>
</msub>
</math>
++++

, g/100 g ^|1,02 ^|0,20 ^|0,80 ^|2,14
|Coefficient of variation of reproducibility, % ^|1,3 ^|0,2 ^|1,0 ^|2,7
|Reproducibility limit, 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mi>R</mi>
</math>
++++

 (= 2,83 

[stem]
++++
<math xmlns="http://www.w3.org/1998/Math/MathML">
<msub>
<mi>s</mi>
<mi>R</mi>
</msub>
</math>
++++

) ^|2,89 ^|0,57 ^|2,26 ^|6,06

|===

