name: prepare

on:
  workflow_call:
    secrets:
      pat_token:
        required: false

jobs:
  prepare-ieee:
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true
    steps:
      - run: mkdir ieee

      - uses: actions/checkout@v3
        with:
          repository: metanorma/ieee-stl
          token: ${{ secrets.pat_token || github.token }}
          path: ieee/stl

      - uses: actions/upload-artifact@v3
        with:
          name: ieee-test-input
          path: |
            ieee/stl/standards-1-7-DTD/standards-1-7-dtd/
